site_name: Purpur Wiki
nav:
    - Home: index.md
    - Configuration: Configuration.md
    - Permissions: Permissions.md
    - Biomes: Biomes.md
repo_url: https://github.com/granny/purpur.wiki.temp
repo_name: granny/purpur.wiki.temp
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  favicon: images/purpur-small.png
  logo: images/purpur-small.png
  palette:
    - scheme: slate
      primary: light blue
      accent: blue
markdown_extensions:
  - toc:
      permalink: 🔗
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg