site_name: Purpur Wiki
# Project information
site_name: Purpur Wiki
site_url: https://pl3xgaming.github.io/PurpurDocs/
site_author: granny
site_description: >-
  The official documentation for Purpur.
  Purpur is a fork of Paper and Tuinity with the goal of providing new and interesting configuration options, which allow for creating a unique gameplay experience not seen anywhere else.

  This wiki was last updated to Build [#945](https://ci.pl3x.net/job/Purpur/945/) ([dd65bd1](https://github.com/pl3xgaming/Purpur/commit/dd65bd110910340703368db9ea3fea5887a2309a))
nav:
    - Home: index.md
    - Configuration: Configuration.md
    - Permissions: Permissions.md
    - Biomes: Biomes.md
repo_url: https://github.com/pl3xgaming/PurpurDocs
repo_name: PurpurDocs
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides
  favicon: images/purpur-small.png
  logo: images/purpur-small.png
  palette:
    - scheme: slate
      primary: light blue
      accent: blue
markdown_extensions:
  - toc:
      permalink: 🔗
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/discord
      link: http://purpur.pl3x.net/discord
      name: Purpur Discord Server