name: Push docs to PurpurWebsite
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Build docs and copy .htaccess
        run: |
          pip install -r requirements.txt
          mkdocs build -d docs

          echo Copying .htaccess to \'docs\' directory
          cp .htaccess docs/
      
      - name: Push to PurpurWebsite repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'docs'
          destination_repo: 'pl3xgaming/PurpurWebsite'
          destination_folder: 'public'
          destination_branch: master
          user_email: 'pkrok01@outlook.com'
          user_name: 'granny'